#### POD config (run one time)
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: headless-rdp
  labels:
    application: headless-rdp
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        application: headless-vnc
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: headless-rdp
        image: <name goes here consol/centos-xfce-vnc>
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          #- '--tail-log'
        ### checks that rdp server is up and running
        livenessProbe:
          tcpSocket:
            port: 3389
          initialDelaySeconds: 1
          timeoutSeconds: 1
        ### checks if http-rdp connection is working
        readinessProbe:
          httpGet:
            path: /
            port: 3389
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: headless-rdp
  name: headless-rdp
spec:
  externalName: headless-rdp
  ports:
  - name: rdp-port-tcp
    protocol: TCP
    port: 3389
    targetPort: 3389
    nodePort: 32001
  selector:
    application: headless-rdp
  type: LoadBalancer
